default['curator']['cron']['user'] = "root"
default['curator']['cmd_path'] = "/usr/bin/curator"
default['curator']['cron']['hour'] = "5"
default['curator']['cron']['minute'] = "37"
default['curator']['days']['close'] = "93"
default['curator']['days']['delete'] = "366"
default['curator']['es']['host'] = "localhost"
default['curator']['es']['index'] = "logstash-"
